
var all = d3.select("#graph")
          .append('div')
          .attr('class', 'step3graph')
          .append("svg")
          .attr("width", W/2)
          .attr("height", H/2)
          .append("g")
all.append ("cicle")
         .attr("cx", 50)
         .attr("cy", 30)
         .attr("r", 20 )
         .style("fill","blue")
         .style("fill-opacity", 0.5)
